server:
  port: 8080

#公众号配置
wechat:
  appId: 你的appId
  appSecret: 你的appSecret
  tempId: 你的模板id
  myBirthday: 你的生日 yyyy-MM-dd
  babyBirthday: 同上
  loveDay: 同上

  tiangouTempId: 舔狗模板id
  tiangouDay: 你的生日 yyyy-MM-dd


#彩虹屁接口
tianapi:
  appKey: 天行appKey
  area: XX市
