server:
  port: 8080

#公众号配置
wechat:
  appId: wx7dbf4e970f5fa297
  appSecret: 752dce4ade5b775774545e6c740a1ba7
  tempId: EzG7zfwIMmSCGZs_3hEnVTgf0Wn_G2nhd2UXOBWJdq4
  myBirthday: 1999-09-17
  babyBirthday: 1999-10-07
  loveDay: 2022-08-22

  tiangouTempId: WxouNL6y4lFzVg0I7_MXUoaVjCtNGYBcSeIXatAB8Y8
  tiangouDay: 1999-09-17


#彩虹屁接口
tianapi:
  appKey: 6f09a5dd755cefbfa844da270761d92b
  area: 深圳市
